config = {'train_data_path':['$DOWNLOADLUNA16PATH/subset9/',
                             '$DOWNLOADLUNA16PATH/subset1/',
                             '$DOWNLOADLUNA16PATH/subset2/',
                             '$DOWNLOADLUNA16PATH/subset3/',
                             '$DOWNLOADLUNA16PATH/subset4/',
                             '$DOWNLOADLUNA16PATH/subset5/',
                             '$DOWNLOADLUNA16PATH/subset6/',
                             '$DOWNLOADLUNA16PATH/subset7/',
                             '$DOWNLOADLUNA16PATH/subset8/'],
          'val_data_path':['$DOWNLOADLUNA16PATH/subset0/'], 
          'test_data_path':['$DOWNLOADLUNA16PATH/subset0/'], 
          
          'train_preprocess_result_path':'$LUNA16PROPOCESSPATH/', # contains numpy for the data and label, which is generated by prepare.py
          'val_preprocess_result_path':'$LUNA16PROPOCESSPATH/',  # make sure copy all the numpy into one folder after prepare.py
          'test_preprocess_result_path':'$LUNA16PROPOCESSPATH/',
          
          'train_annos_path':'$LUNA16ANNOTATIONPATH/luna16/CSVFILES/annotations.csv',
          'val_annos_path':'$LUNA16ANNOTATIONPATH/luna16/CSVFILES/annotations.csv',
          'test_annos_path':'$LUNA16ANNOTATIONPATH/luna16/CSVFILES/annotations.csv',

          'black_list':[],
          
          'preprocessing_backend':'python',
         } 
